-- Generated by flux-theme-set — do not edit, re-run: flux-theme-set <name>
hl.config({
  general = {
    col = {
      active_border = { colors = { "rgba(8fcaa3ee)", "rgba(8fcaa366)" }, angle = 45 },
      inactive_border = "rgba(8b949e66)",
    },
  },
})
