-- FluxLinux default Hyprland configuration
-- Hyprland 0.55+ Lua config; .conf format support is removed in 0.57.
-- See https://wiki.hypr.land/Configuring/Start/

local home = os.getenv("HOME")

local mod = "SUPER"
local terminal = "kitty"
local menu = "flux-menu"
local fileManager = "thunar"

------------------
---- MONITORS ----
------------------

hl.monitor({
  output = "",
  mode = "preferred",
  position = "auto",
  scale = "auto",
})

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
  hl.exec_cmd("waybar")
  hl.exec_cmd("mako")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("hyprsunset")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- Dark mode for GTK3/GTK4 apps (thunar, pavucontrol, file-roller, ...)
hl.env("GTK_THEME", "Adwaita:dark")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
  input = {
    kb_layout = "us",
    follow_mouse = 1,
    touchpad = {
      natural_scroll = true,
    },
  },

  general = {
    gaps_in = 5,
    gaps_out = 12,
    border_size = 2,
    layout = "dwindle",
    resize_on_border = true,
    allow_tearing = false,
  },

  decoration = {
    rounding = 0,
    active_opacity = 1.0,
    inactive_opacity = 0.94,

    shadow = {
      enabled = true,
      range = 16,
      render_power = 3,
      color = "rgba(00000066)",
    },

    blur = {
      enabled = true,
      size = 6,
      passes = 3,
      new_optimizations = true,
      ignore_opacity = true,
    },
  },

  animations = {
    enabled = true,
  },

  dwindle = {
    preserve_split = true,
  },

  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
  },
})

-- Theme-provided border colors; regenerated by flux-theme-set.
dofile(home .. "/.config/fluxlinux/theme/hyprland-colors.lua")

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("flux", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "flux", style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "flux", style = "popin 80%" })
hl.animation({ leaf = "fade", enabled = true, speed = 4, bezier = "flux" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "flux", style = "slide" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "flux" })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Blur/round the panels that sit above windows
hl.layer_rule({ match = { namespace = "^(waybar|notifications|launcher|weather-popup|background-switcher)$" }, blur = true })
hl.layer_rule({ match = { namespace = "waybar" }, ignore_alpha = 0 })

hl.window_rule({ match = { class = "^(kitty)$" }, opacity = "0.96 0.9" })
hl.window_rule({ match = { class = "^(pavucontrol|blueman-manager|nm-connection-editor)$" }, float = true })

-- Branded floating overlay (flux-overlay wrapper)
hl.window_rule({
  match = { class = "^(flux-overlay)$" },
  float = true,
  center = true,
  size = "760 640",
  pin = true,
  border_color = "rgba(8fcaa3ff)",
  opacity = "1.0 1.0",
})

---------------------
---- KEYBINDINGS ----
---------------------

-- `description` on every bind keeps flux-keybindings (SUPER + K) working:
-- it reads these back live from `hyprctl binds -j` instead of grepping a
-- config file, since Lua binds report as an opaque dispatcher there.
hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd(terminal), { description = "Open terminal" })
hl.bind(mod .. " + SPACE", hl.dsp.exec_cmd(menu), { description = "App launcher" })
hl.bind(mod .. " + ALT + SPACE", hl.dsp.exec_cmd("flux-menu apps"), { description = "App launcher (apps)" })
hl.bind(mod .. " + SHIFT + SPACE", hl.dsp.exec_cmd("flux-app-menu"), { description = "App menu" })
hl.bind(mod .. " + M", hl.dsp.exec_cmd("flux-menu"), { description = "App launcher" })
hl.bind(mod .. " + E", hl.dsp.exec_cmd(fileManager), { description = "File manager" })
hl.bind(mod .. " + B", hl.dsp.exec_cmd("firefox"), { description = "Firefox" })
hl.bind(mod .. " + W", hl.dsp.window.close(), { description = "Close window" })
hl.bind(mod .. " + SHIFT + E", hl.dsp.exec_cmd("hyprctl dispatch exit"), { description = "Exit Hyprland" })
hl.bind(mod .. " + CTRL + L", hl.dsp.exec_cmd("hyprlock"), { description = "Lock screen" })
hl.bind(mod .. " + ESCAPE", hl.dsp.exec_cmd("flux-power-menu"), { description = "Power menu" })
hl.bind(mod .. " + CTRL + V", hl.dsp.exec_cmd("flux-clipboard-menu"), { description = "Clipboard menu" })
hl.bind(mod .. " + CTRL + N", hl.dsp.exec_cmd("flux-toggle-nightlight"), { description = "Toggle night light" })
hl.bind(mod .. " + CTRL + E", hl.dsp.exec_cmd("flux-emoji-menu"), { description = "Emoji menu" })
hl.bind(
  mod .. " + K",
  hl.dsp.exec_cmd("flux-keybindings"),
  { description = "Show keybindings" }
)

hl.bind(mod .. " + COMMA", hl.dsp.exec_cmd("makoctl dismiss"), { description = "Dismiss notification" })
hl.bind(mod .. " + SHIFT + COMMA", hl.dsp.exec_cmd("makoctl dismiss -a"), { description = "Dismiss all notifications" })
hl.bind(mod .. " + CTRL + COMMA", hl.dsp.exec_cmd("makoctl mode -t silent"), { description = "Toggle silent notifications" })
hl.bind(mod .. " + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreen"), { description = "Fullscreen" })
hl.bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })

hl.bind(mod .. " + H", hl.dsp.focus({ direction = "l" }), { description = "Focus left" })
hl.bind(mod .. " + L", hl.dsp.focus({ direction = "r" }), { description = "Focus right" })
hl.bind(mod .. " + SLASH", hl.dsp.focus({ direction = "u" }), { description = "Focus up" })
hl.bind(mod .. " + J", hl.dsp.focus({ direction = "d" }), { description = "Focus down" })

hl.bind(mod .. " + SHIFT + H", hl.dsp.window.swap({ direction = "l" }), { description = "Move window left" })
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.swap({ direction = "r" }), { description = "Move window right" })
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.swap({ direction = "u" }), { description = "Move window up" })
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.swap({ direction = "d" }), { description = "Move window down" })

for workspace = 1, 5 do
  hl.bind(mod .. " + " .. workspace, hl.dsp.focus({ workspace = workspace }), { description = "Workspace " .. workspace })
  hl.bind(
    mod .. " + SHIFT + " .. workspace,
    hl.dsp.window.move({ workspace = workspace }),
    { description = "Move window to workspace " .. workspace }
  )
end

-- Screenshot region -> clipboard and ~/Pictures/Screenshots
hl.bind(
  mod .. " + SHIFT + S",
  hl.dsp.exec_cmd(
    "bash -lc 'mkdir -p \"$HOME/Pictures/Screenshots\"; f=\"$HOME/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png\"; grim -g \"$(slurp)\" \"$f\" && wl-copy < \"$f\"'"
  ),
  { description = "Screenshot region" }
)

hl.bind(
  "XF86AudioRaiseVolume",
  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),
  { locked = true, repeating = true, description = "Volume up" }
)
hl.bind(
  "XF86AudioLowerVolume",
  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
  { locked = true, repeating = true, description = "Volume down" }
)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, description = "Mute" })
hl.bind(
  "XF86MonBrightnessUp",
  hl.dsp.exec_cmd("brightnessctl set +5%"),
  { locked = true, repeating = true, description = "Brightness up" }
)
hl.bind(
  "XF86MonBrightnessDown",
  hl.dsp.exec_cmd("brightnessctl set 5%-"),
  { locked = true, repeating = true, description = "Brightness down" }
)

hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Move window (drag)" })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window (drag)" })
