# FluxLinux default fuzzel (app launcher) config

[main]
font=monospace:size=12
dpi-aware=auto
terminal=kitty
prompt=
placeholder=Go…
icon-theme=hicolor
icons-enabled=yes
lines=10
minimal-lines=yes
width=26
horizontal-pad=18
vertical-pad=18
inner-pad=6
line-height=32

[border]
width=2
radius=10
selection-radius=6

[key-bindings]
prev=Up
next=Down

[colors]
background=0c0e12ff
text=e8edf2ff
placeholder=8b949eff
prompt=e8edf294
input=e8edf2ff
match=8fcaa3ff
selection=e8edf214
selection-text=8fcaa3ff
selection-match=8fcaa3ff
counter=8b949eff
border=e8edf2ff
